=== Sameena-Fathima/Internship-Training-Exercises/assignment/invoice.dtd
<!ELEMENT invoices (invoice+)>
<!ELEMENT invoice (sno,itemname,price,quantity,amount)>
<!ELEMENT sno (#PCDATA)>
<!ELEMENT itemname (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT amount (#PCDATA)>

=== Sameena-Fathima/Internship-Training-Exercises/assignment/invoice.xml
<!DOCTYPE invoices SYSTEM "invoice.dtd">
<invoices>
	<invoice>
		<sno>1</sno>
		<itemname>Snickers</itemname>
		<price>20</price>
		<quantity>10</quantity>
		<amount>200</amount>
	</invoice>
	<invoice>
		<sno>2</sno>
		<itemname>Munch</itemname>
		<price>10</price>
		<quantity>10</quantity>
		<amount>100</amount>
	</invoice>
</invoices>
