=== Sameena-Fathima/Internship-Training-Exercises/rmiserver/invoice.dtd
<!ELEMENT invoice (invoiceno,invoicedate,customer+,items+)>
<!ELEMENT invoiceno (#PCDATA)> 
<!ELEMENT invoicedate (#PCDATA)>
<!ELEMENT customer (customerno,customername,customeraddress,customeremail,customerphno)>
<!ELEMENT customerno (#PCDATA)>
<!ELEMENT customername (#PCDATA)>
<!ELEMENT customeraddress (#PCDATA)>
<!ELEMENT customeremail (#PCDATA)>
<!ELEMENT customerphno (#PCDATA)>  
<!ELEMENT items (item+)>
<!ELEMENT item (itemno,itemname,unit,price,quantity,total)>
<!ELEMENT itemno (#PCDATA)>
<!ELEMENT itemname (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT unit (#PCDATA)> 
<!ELEMENT total (#PCDATA)>

=== Sameena-Fathima/Internship-Training-Exercises/rmiserver/invoice.xml
<!DOCTYPE invoice SYSTEM "invoice.dtd"><invoice><invoiceno>2</invoiceno><invoicedate>2021-03-22</invoicedate><customer><customerno>102</customerno><customername>Reema</customername><customeraddress>Chennai</customeraddress><customeremail>reema@gmail.com</customeremail><customerphno>9882445992</customerphno></customer><items><item><itemno>1</itemno><itemname>Maaza</itemname><unit>1.5 liters</unit><price>80</price><quantity>2</quantity><total>160</total></item><item><itemno>2</itemno><itemname>Bovonto</itemname><unit>1.5 liters</unit><price>65</price><quantity>2</quantity><total>130</total></item></items></invoice>
